# This is the default pipeline – it will build and test the app

env:
  IMAGE_ID: $IMAGE_ID

steps:
  - label: "🔬 Build and Test"
    command: .buildkite/commands/build-and-test.sh
    plugins: [$CI_TOOLKIT_PLUGIN]
    agents:
      queue: mac

  - label: ":swift: SwiftLint"
    command: run_swiftlint --strict
    plugins: [$CI_TOOLKIT_PLUGIN]
    notify:
      - github_commit_status:
          context: "SwiftLint"
    agents:
      queue: default

  - label: "🛠 Verify App Store Target Builds"
    command: .buildkite/commands/build-and-test-app-store.sh
    plugins: [$CI_TOOLKIT_PLUGIN]
    agents:
      queue: mac
